### PR TITLE
use hls stream playlist including audio stream for playback

### PR DESCRIPTION
**Pull request by krisek**
Fixing issue #1 

Tested on Linux and Android, live streams have sound now. Audio delay might need to be adjusted during playback.

### CODE REVIEW

**Comment by vargalex** [comment]
The main problem is, as you soon wrote, that the video and audio streams are splitted. With your solution is OK, but you cannot switch between different resolutions. I don't know, which one video stream selects Kodi automatically...

**Comment by krisek** [comment]
I always thought that HLS prescribes to take the stream which can be buffered in a reasonable time, ie. it is an adaptive selection according the available bandwidth. Just checked, you can 'lock' to a specific video stream in the playback settings menu (right side gear on the playback control)/Select program option. Actually this is really useful in situations where the network is not reliable or there is some bandwidth limitation (like the servers are overloaded).

**Comment by vargalex** [comment]
I checked soon, by me was the best resolution played.

**Comment by Fredrik-Smartoptics** [comment]
Hi. I just want to thank you guys for fixing this. My hungarian stepmother 86 eves lives here in sweden and moved from her house recently. There she had hungarian channels through parabol. But now I wanted to find a good internet solution and you fixed it. Perfect video and audio and (hopefully) the streams will not stop working like they do with IPTV solutions where it is hard to find a long lasting URL that doesn't suddenly stop working. So thanks again, you made a good deed today.

**Comment by krisek** [comment]
Sure, no problem @vargalex elég pöpec ez a plugin, le a kalappal és köszi :)

**Pull request merged**
